### ISSUE TITLE
`cargo test` takes 8x more time on my laptop after the switch to Miden VM v0.10.5 (from v0.10.3)

### ISSUE THREAD

**Issue by greenhat** [0xMiden/compiler#317]
After the switch to Miden VM v0.10.5 in https://github.com/0xPolygonMiden/compiler/commit/65365a033936e042edd8be745af070d9dce6cf6e the `cargo test` takes 16 minutes on my laptop instead of 2 minutes before the switch.
Interestingly, on CI time went up only from ~19 minutes to ~32 minutes. I suspect with more cores, the performance degrades more quickly.

**Comment by greenhat** [comment]
![flamegraph](https://github.com/user-attachments/assets/4cc68095-3418-4a63-bc7f-dc3204d9674b)

The flamegraph for one of the tests is generated via:
```shell
cargo flamegraph --root --unit-test miden_integration_tests -- rust_masm_tests::instructions::band_i64
```

**Comment by greenhat** [comment]
![flamegraph](https://github.com/user-attachments/assets/ed01c231-21f9-4f54-aaf4-0b25d9211c00)
And here is the same test at https://github.com/0xPolygonMiden/compiler/commit/202cb9f090c1e9075456e711b2656a6a92fe502a (previous commit, with Miden VM v0.10.3) taking 1/10 time of the above.

**Comment by plafer** [comment]
Interesting that changes in 0.10.5 caused this... Are you able to zoom in to the `Assembler` methods to get a better sense of where the time is being spent?

Side note: I use `cargo nextest` locally which is a faster test runner (although this is a not a fix to the above regression!)

**Comment by greenhat** [comment]
> Interesting that changes in 0.10.5 caused this... Are you able to zoom in to the `Assembler` methods to get a better sense of where the time is being spent?

Thank you for looking into it. For some reason, when you click on the svg file it opens in the separate tab and zooming does not work, but the mouse-over displays full text. However, if you download the svg file and open the local file, zooming works nicely.

> Side note: I use `cargo nextest` locally which is a faster test runner (although this is a not a fix to the above regression!)

Yes, we use it as well, but here it is not much help.

The test is running the compiled MAST on the VM 256 times using https://github.com/0xPolygonMiden/compiler/blob/173c48b106c06f87b432c1a2ce2807727b484463/tests/integration/src/rust_masm_tests/mod.rs#L23-L40
I suspect starting and/or shutting down the VM instance became more expensive.

**Comment by bobbinth** [comment]
My guess is that it has something to do with loading the standard library into the assembler/processor. Are we able to run this against the `next` branch and see if it still happens?

**Comment by bobbinth** [comment]
Although, the main thing that changed between 10.3 and 10.5 was the merging of adjacent basic blocks - but that shouldn't have such a big impact.

**Comment by bitwalker** [comment]
The major increase in time here is 100% due to the loading of the standard library, though a subsequent commit modified the compiler to cache the standard library after it is loaded, and simply clone it after that. A similar change was made in the VM, though I can't recall if that has been released yet.

This was initially noticed by me when we turned on implicit linking of the standard library (since we went from not linking against it at all in many tests, to linking it in all of them), but the actual overhead comes from the hashing done when loading the MAST.

This should be fixed in the current `next` of the compiler though, it certainly isn't taking me 19 minutes to run the test suite, but maybe we've had a regression somehow (possibly due to the transaction kernel library being implicitly linked when `--target rollup` is set). Did this come up when doing `cargo-miden` changes, maybe it is related to that, since I think `cargo-miden` always sets `--target rollup`, and we haven't done the caching "trick" we did with the standard library there yet.

**Comment by greenhat** [comment]
> My guess is that it has something to do with loading the standard library into the assembler/processor. Are we able to run this against the `next` branch and see if it still happens?

I run our tests using almost the tip of the Miden VM `next` branch -   https://github.com/0xPolygonMiden/miden-vm/commit/1b4609e60e6409a7f0d66bd13cfdc8320ab2727c (the `lazy_lock` introduced in 
https://github.com/0xPolygonMiden/miden-vm/commit/0ce2fe519353de7f7b71ce627c6ab99eec842170 is still unstable in our rustc version) and it resolved the issue! The `cargo test` is back to under 2 minutes on my laptop. 
I made #319 to switch to it.

**Comment by greenhat** [comment]
> The major increase in time here is 100% due to the loading of a MAST library, though a subsequent commit to the one you linked modified the compiler to cache the standard library after it is loaded, and simply clone it after that. A similar change was made in the VM, though I can't recall if that has been released yet.
> 
> This was initially noticed by me when we turned on implicit linking of the standard library (since we went from not linking against it at all in many tests, to linking it in all of them), but the actual overhead comes from the hashing done when loading the MAST.
> 
> This should be fixed in the current `next` of the compiler though, it certainly isn't taking me 16 minutes to run the test suite, but maybe we've had a regression somehow (possibly due to the transaction kernel library being implicitly linked when `--target rollup` is set). 

I'm still getting the same ~16 minutes (just tested and got 15 and a half minutes) in the `next` branch.
How much time does `cargo test` take on your machine? I believe we have the same laptop model, so we should see comparable results.

> Did this come up when doing `cargo-miden` changes, maybe it is related to that, since I think `cargo-miden` always sets `--target rollup`, and we haven't done the caching "trick" we did with the standard library there yet.

Nope, I've been experiencing this issue since last week on the `next` branch, so I started digging and was able to find the commit after which it started - https://github.com/0xPolygonMiden/compiler/commit/65365a033936e042edd8be745af070d9dce6cf6e

**Comment by bitwalker** [comment]
> How much time does cargo test take on your machine? I believe we have the same laptop model, so we should see comparable results.
> 
> so I started digging and was able to find the commit after which it started - https://github.com/0xPolygonMiden/compiler/commit/65365a033936e042edd8be745af070d9dce6cf6e

I'm able to reproduce the issue, but what I was getting at is that the commit you are referencing was from _before_ the fix that addressed the issue. Meaning that, somehow, our fix is no longer working. I definitely want to get to the bottom of that, even if it can be fixed by updating the VM deps to use git temporarily, as it means we are doing something, somewhere, that we shouldn't be.

**Comment by bobbinth** [comment]
In `next`, we should be handling `miden-stdlib` very efficiently. The deserialization shouldn't involve any hashing and it should be done only once per process (because a static variable is used to hold the deserialized library). `miden-base` is not using static variables yet, but it should also be pretty efficient (i.e., no hashing on deserialization). So, I'm very curious what's causing the issue here.

(it is of course possible that something in the above doesn't work as expected).

**Comment by bitwalker** [comment]
@bobbinth To be clear, the issue here is in the latest published release, not `next`.

One thing I did notice when examining the flamegraph, is that dropping the vectors used to store the decorators gets really expensive when you have a decorator attached to every node in the program (when debug info is enabled, as it always is in the compiler currently) - ~30% of the program runtime is spent just on dropping those.

Now, on to the actual issue, and the reason why it appears to be fixed in `next`:

Because `next` has switched to allocating libraries in `Arc`, and doling out clones of the pointer, rather than the library data itself, this issue will only present itself when dropping libraries that aren't effectively immortal like `miden-stdlib` and `miden-base`, but the "fix" here is only for the narrow case of those two libraries, which are allocated and cached the first time they are loaded, so the drops never happen. It will still continue to affect programs consisting of many libraries, or large libraries, as soon as all of the live `Arc` references are dropped.

/cc @greenhat
